CONNECT sh@TESTDB/sh
SET AUTOT TRACE EXP STAT
SELECT CUST_FIRST_NAME, CUST_LAST_NAME, CUST_CITY
FROM CUSTOMERS
ORDER BY CUST_CITY;

SET AUTOT TRACE EXP STAT
SELECT DISTINCT CUST_CITY FROM CUSTOMERS;
 
SET AUTOT TRACE EXP STAT
SELECT CUST_CITY, COUNT(*) FROM CUSTOMERS GROUP BY CUST_CITY;

CREATE INDEX IX_CUST_CITY ON CUSTOMERS(CUST_CITY, CUST_LAST_NAME, CUST_FIRST_NAME);

SET AUTOT TRACE EXP STAT
SELECT CUST_FIRST_NAME, CUST_LAST_NAME, CUST_CITY
FROM CUSTOMERS
ORDER BY CUST_CITY;

SET AUTOT TRACE EXP STAT
SELECT DISTINCT CUST_CITY FROM CUSTOMERS;
 
SET AUTOT TRACE EXP STAT
SELECT CUST_CITY, COUNT(*) FROM CUSTOMERS GROUP BY CUST_CITY;

SET AUTOT OFF
DROP INDEX IX_CUST_CITY;


SET AUTOT TRACE EXP STAT
SELECT DISTINCT CUST_CITY FROM CUSTOMERS ORDER BY CUST_CITY;
SELECT CUST_CITY, COUNT(*) FROM CUSTOMERS GROUP BY CUST_CITY ORDER BY CUST_CITY;

CREATE INDEX IX_CUST_CITY ON CUSTOMERS(CUST_CITY, CUST_LAST_NAME, CUST_FIRST_NAME);

SET AUTOT TRACE EXP 
SELECT DISTINCT CUST_CITY FROM CUSTOMERS ORDER BY CUST_CITY;
SELECT CUST_CITY, COUNT(*) FROM CUSTOMERS GROUP BY CUST_CITY ORDER BY CUST_CITY;

SET AUTOT OFF
DROP INDEX IX_CUST_CITY;
