CONNECT sh@TESTDB/sh

SELECT CUST_ID, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_YEAR_OF_BIRTH
FROM CUSTOMERS
WHERE ROWNUM < 11
ORDER BY CUST_YEAR_OF_BIRTH DESC;

SELECT * FROM (
  SELECT CUST_ID, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_YEAR_OF_BIRTH
  FROM CUSTOMERS
  ORDER BY CUST_YEAR_OF_BIRTH DESC
)
WHERE ROWNUM < 11;

SELECT * FROM (
  SELECT CUST_ID, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_YEAR_OF_BIRTH, 
  RANK() OVER (ORDER BY CUST_YEAR_OF_BIRTH DESC) AS RANKING 
  FROM CUSTOMERS
)
WHERE RANKING < 11;

SELECT * FROM (
  SELECT CUST_ID, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_YEAR_OF_BIRTH, 
  DENSE_RANK() OVER (ORDER BY CUST_YEAR_OF_BIRTH DESC) AS RANKING 
  FROM CUSTOMERS
)
WHERE RANKING < 11;


SET AUTOT TRACE EXP STAT
SELECT * FROM (
  SELECT CUST_ID, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_YEAR_OF_BIRTH
  FROM CUSTOMERS
  ORDER BY CUST_YEAR_OF_BIRTH DESC
)
WHERE ROWNUM < 11;

SELECT * FROM (
  SELECT CUST_ID, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_YEAR_OF_BIRTH, 
  RANK() OVER (ORDER BY CUST_YEAR_OF_BIRTH DESC) AS RANKING 
  FROM CUSTOMERS
)
WHERE RANKING < 11;

SELECT * FROM (
  SELECT CUST_ID, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_YEAR_OF_BIRTH, 
  DENSE_RANK() OVER (ORDER BY CUST_YEAR_OF_BIRTH DESC) AS RANKING 
  FROM CUSTOMERS
)
WHERE RANKING < 11;

SET AUTOT OFF

SET TIMING ON
SELECT * FROM (SELECT * FROM sh.SALES ORDER BY AMOUNT_SOLD DESC) WHERE ROWNUM < 11;
SELECT * FROM (SELECT S.*, DENSE_RANK() OVER (ORDER BY AMOUNT_SOLD DESC) AS RANKING FROM sh.SALES S) WHERE ROWNUM < 11;
SET TIMING OFF
